### ISSUE TITLE
How to generate a multi-fasta alignement between contigs and a reference genome?

### ISSUE THREAD

**Issue by aliabenkahla** [tseemann/snippy#126]
Dear Colleague(s),

I am contacting you concerning SNIPPY.

I would like to use it to generate a muti-fasta alignment between contigs and a reference genome.
Is that possible?
If yes, how to do it?

Many thanks,
Best,
Alia.

**Comment by tseemann** [comment]
If you are interested in a proper whole genome alignment between your sets of contigs, you should use Mauve by @koadman from http://darlinglab.org/mauve/mauve.html

If you want to use Snippy you can use the `--ctgs` option instead of `--R1` and `--R2`.

For example, you have `ref.fa`, `1.fa`, `2.fa`, `3.fa` contigs:

```
snippy --ref ref.fa --ctgs 1.fa --outdir out1
snippy --ref ref.fa --ctgs 2.fa --outdir out2
snippy --ref ref.fa --ctgs 3.fa --outdir out3
snippy-core out1 out2 out3
```
Then the `core.full.aln` file is what you (probably) want.

**Comment by aliabenkahla** [comment]
Mauve doesn't produce a multi-fasta alignment file that could go as input to gubbins.

Thank you very much. snippy woks perfectly.

Best,
Alia.
