### ISSUE TITLE
Is it possible to use a consensus as the reference genome?

### ISSUE THREAD

**Issue by k3lvie** [tseemann/snippy#177]
Hi, 
I have been downloading a reference genome to use in my analyses.
In the next stage of analysis, I would like to compare between my own samples. Therefore I would like to assign one of my sample as the reference instead.

In trying to do so, I have generated a consensus of one sample (after mapping to a reference genome). When exporting the consensus, I have made sure that I kept the name short and also wrapped the sequence sample to 80 char.

I have tried the same command with the original reference genome and it worked fine.
Not sure what I am doing wrong here.
[snps.log](https://github.com/tseemann/snippy/files/2089085/snps.log)

Thanks.
Kelvin :)

**Comment by tseemann** [comment]
```
The fasta sequence does not match the REF at cons16SRHH060:158857. STGM(TGMTCCTTT) in .fa, NTGN in .vcf, frz=154865
 at /home/ubuntu/snippy/bin/../binaries/noarch/vcf-consensus line 20, <STDIN> line 2649.
	main::error("The fasta sequence does not match the REF at cons16SRHH060:15"...) called at /home/ubuntu/snippy/bin/../binaries/noarch/vcf-consensus line 262
	main::apply_variant(HASH(0x1192f30), ARRAY(0x16adf20)) called at /home/ubuntu/snippy/bin/../binaries/noarch/vcf-consensus line 146
	main::do_consensus(HASH(0x1192f30)) called at /home/ubuntu/snippy/bin/../binaries/noarch/vcf-consensus line 11
```

**Comment by tseemann** [comment]
i think the problem is your reference has N and other characters in it.
The consensus from Snippy 3 will have characters like `-` and `N`.
Snippy 4 will have `X` and `n` as well.

You are better off de novo assembling one of your samples with  Spades and use that.

OR

Use `snippy-core` to look at differences between your 2 samples, using the reference as a middle-man/proxy.
