### ISSUE TITLE
How does snippy deal with recombination events?

### ISSUE THREAD

**Issue by phiweger** [tseemann/snippy#197]
Say I have a set of genomes but some have an inversion of some gene -- what is Snippy's way to deal with those? 

My intuition would be that reads that do not cover the boundaries of the recombination will be used to call SNPs but reads across boundaries will probably be lost in the mapping step, meaning less "SNP resolution" close to these boundaries -- is that correct?

Thank you.

**Comment by tseemann** [comment]
An inversion of a single (bacterial) gene - wow that is quite interesting.   
Would one still consider that "recombination" ? (i guess so, but not "homologous recombination" ?)

Due to the inversion, reads will only partially map yes, and have secondary or supplementary alignments, relative to the reference.

Snippy 4 removes anything that only partially aligns via the `--softmax` soft-clipping parameter. 

But yes, you won't get variants at the new junctions.

You might want to try Breseq which might handle this much better:
http://barricklab.org/twiki/bin/view/Lab/ToolsBacterialGenomeResequencing
