### ISSUE TITLE
freebayes-parallel Error: --tollef has been retired.

### ISSUE THREAD

**Issue by scottishwormboy** [tseemann/snippy#225]
conda install of snippy

(snippy) stevep11@watt26:~/Datafiles/Pseudo/LIMS14437$ snippy --version
snippy 4.0.5

snippy --check is fine

 
snippy --cpus 16 --outdir ${wkdir}/snippy/tst --ref ${ref}.gbk --R1 ${R1} --R2 ${R2}

[snps.log](https://github.com/tseemann/snippy/files/2310171/snps.log)

tail of log file
### freebayes-parallel reference/ref.txt 16 -p 2 -P 0 -C 10 --min-repeat-entropy 1.5 --strict-vcf -q 13 -m 60 --min-coverage 10 -F 0.05 -f reference/ref.fa snps.bam > snps.raw.vcf

parallel: Error: --tollef has been retired.
parallel: Error: Remove --tollef or use --gnu to override --tollef.

(snippy) stevep11@watt26:~/Datafiles/Pseudo/LIMS14437$ parallel --version
GNU parallel 20180522

**Comment by tseemann** [comment]
This is a very old error that I used to get from some people who were using a very old version of `parallel` or had an `/etc/parallel.parallel.conf` file with weird settings in it.

As conda, it might be in `$CONDA_HOME/etc/` too.
Or `~/.parallel/config`
Or the `$PARALLEL` variable may point to it.

You can probablty add `--gnu` to one of those files.

OR

Edit the script (find it with `which freebayes-parallel`) and try adding `--gnu` to it?

```
cat "$regionsfile" | parallel ==gnu -k -j "$ncpus" "${command[@]}" --region {}
```

Because I don't control either of those packages there is not much i can do.

**Comment by scottishwormboy** [comment]
Thanks, edited freebayes parallel and worked a treat
