### ISSUE TITLE
FreeBayes ploidy:

### ISSUE THREAD

**Issue by EisenRa** [tseemann/snippy#233]
Hi Torsten,

Just a quick question re. the default ploidy level for the variant calling step. Is there a reason that the default FreeBayes option for SNIPPY is -p2 (diploid)?

Thanks again for building this pipeline!

Best regards,
Raphael

**Comment by tseemann** [comment]
Snippy 3.x used to use `-p 1` but it causes lots of problems, because if the SNP caller assumes it is haploid, then as soon as it gets some evidence that there may be a mixed site (eg. REF 50 A vs ALT 20 T) then it will call it as genotype `1` because it clearly is not homozygous. But in actual fact it is due to bad mapping or some repeat artifact due to short reads. By calling in diploid mode it allows me to filter out dodgy calls.

But it is a fair question!
