### ISSUE TITLE
Contig shredding coverage with --ctgs

### ISSUE THREAD

**Issue by keithbg** [tseemann/snippy#253]
In the section on the README file below states that when using the `--ctgs` option snippy will shred contigs into reads at 2x the `--mincov` value. I have been running snippy with `--mincov` values of 10 (default), 30, and 40. When I look at the bam files they all show coverage values of ~20. Now my impression is that the `--ctgs` command shreds contigs into reads at coverage value of 20, and that changing the `--mincov` argument in the `snippy` command will not affect the read coverage. Is this how you intend the program to run? If so, could you clarify the README document, so it is clear that the coverage value is a fixed value. 

I was trying to increase the coverage of the shredded contigs to improve SNP detection, I realize now, I should be lowering the `--mincov`. I stumbled across issue #50, which helped me understand the pattern I was seeing in my bam files.  

**Finding SNPs between contigs**
Sometimes one of your samples is only available as contigs, without corresponding FASTQ reads. You can still use these contigs with Snippy to find variants against a reference. It does this by shredding the contigs into 250 bp single-end reads at `2 &times; --mincov uniform` coverage.

**Comment by tseemann** [comment]
The documentation is correct. 
The _code_ is wrong.

However, if you have contigs only, then `--mincov` is actually irrelevant.  we could 1x coverage and still get the same ability to detect SNPs, because we know all the reads are fake and there is no errors in the reads. Maing `--mincov` higher with `--ctgs` just wastes CPU time.

I have edited the code to ensure I shred to `2 x --mincov` so this won't accidently cause problems in the future.
