### ISSUE TITLE
Different results in .aligned.fa and vcf with the same reference 

### ISSUE THREAD

**Issue by edgarom** [tseemann/snippy#274]
As I was playing with snippy, I came across something strange. 

I pass to snippy different files of reference;

  a) multifasta with different genomes of influenza among them is the  sequence of main interes for me (>gb:KU976802), and I have a vcf file with 24 variants 

 b) the file fasta with  single sequence of reference (>gb:KU976802), I have a vcf with the 4 variant 

 c) multifasta with the several reference of same gene but differen isolates, I don't have any consensus   .
I know that the results are not properly from the pipe of snippy if not from bwa, but will know why this result happens ?

**Comment by andersgs** [comment]
The question seems to imply that you are passing to snippy a multiFASTA reference file to the `--ref` flag. But, the multiFASTA has several sequences that are largely the same. If that is so, then I would expect to see no SNPs because reads mapping to multiple locations will be removed. 

If you are looking to align multiple sequences, snippy is probably not your best choice. But, you could pick one sequence as the reference, and feed the others using the `--ctgs` flag. One run of snippy per sequence. Then run `snippy-core`. 

You can use `snippy-multi` as a shortcut: `snippy-multi --help`
