### ISSUE TITLE
freebayes call params

### ISSUE THREAD

**Issue by phiweger** [tseemann/snippy#294]
Hi and thank you for this awesome piece of software!

I ran snippy w/ default params and got curious when it printed the call to freebayes:

```

freebayes-parallel reference/ref.txt 8 -p 2 -P 0 -C 10 --min-repeat-entropy 1.5 --strict-vcf -q 13 -m 60 --min-coverage 10 -F 0.05  -f reference/ref.fa snps.bam > snps.raw.vcf 2>> snps.log
```

Why is the ploidy param set to `-p 2` when the main use case of snippy are haploid genomes? Maybe I am missing something very basic here.

Also, when I set `--minfrac` to e.g. 0.5, the call to freebayes still says `-F 0.05` -- does that mean snippy filters the SNVs after they have been called w/ 0.05?

Thank you very much,
Adrian

**Comment by tseemann** [comment]
@phiweger
i use higher ploidy so that I can detect mixed sites. These are usually due to mapping alignment problems and not actual mixed samples. 
This allows me to remove what would otherwise be false positive snp calls.

And yes, the minfrac filtering is done afterwards. This is recommended on the freebayes documentation.

**Comment by phiweger** [comment]
Thanks for the quick reply!
