### ISSUE TITLE
SNPs from metagenomics data

### ISSUE THREAD

**Issue by HweeSze** [tseemann/snippy#296]
Hi, 
firstly, thanks for introducing such great tool for identifying snps in isolates.

I am trying to use the metagenomes-assembled genome (>300 coverage) to map back to the original reads, but the output has >2000 snps, and most of them with ref occurrence =0 , and alternative nucleotide >300, I am thinking that the error correcting steps while assembly actually correct the reads, and produce a bin with "snps", do you think if there is any other way to detect snps in metagenome assembled genomes?

![snippy](https://user-images.githubusercontent.com/47613707/60657838-1b392380-9ea6-11e9-88d2-bda03df5b0a6.PNG)

Thanks,
Sze

**Comment by tseemann** [comment]
I am not sure what you mean.

You have reads, which you de novo assembled into metagenomic contigs?
Then you used Snippy to align those same reads back to the metagenomic contigs?

If so, then Snippy can not help you. It is desgined for isolate sequencing with close references. Metagenome assemblies will only represent the high abundance members of the metagenomic community and hence the reads, when aligned back, will introduce all sorts of weird SNPs due to strain variation in your community,

Perhaps `lofreq` will be more suitable.
