### ISSUE TITLE
Could not run snp-sites

### ISSUE THREAD

**Issue by peflanag** [tseemann/snippy#326]
Hi,

I ran snippy and now I want to run snippy-core. I have cd into the directory where all the files have been generated and ran the following 

snippy-core --mask Path/to/file --ref Path/to/file --prefix Core_SNPs "IMRL28" etc etc for each of the files.

The program starts to work and goes through all the files but when it gets to snp-sites it fails. Any thoughts?

Cheers,

P

![Screenshot 2019-10-29 at 15 51 22](https://user-images.githubusercontent.com/32863969/67784996-84036780-fa64-11e9-8e4f-cb80de7dc972.png)

**Comment by tseemann** [comment]
The `Warning` line before that says you have `No SNPs`.
You can't do any more analysis because amongst your samples there are _no CORE SNPs_.
This usually means one or more of your samples was too distant from the reference, or was a sequencing failure.
Look at your '214' and `243` sample - it has 4 million unaligned bases, so something is wrong.
Remove it from your analysis and try again.
