### ISSUE TITLE
How does snippy deal with "Intra-species" contaminated sample?

### ISSUE THREAD

**Issue by MostafaYA** [tseemann/snippy#341]
Hi Torsten, 
I was wondering how snippy deals with "Intra-species" contaminated sample.
Sometimes unintentionally we sequence a mixed culture of isolates from the same species.  
Mapping the reads to a reference may gives multiple possible variants at a single position. 
Does snippy choose the one with the higher coverage? 
Can snippy help us to detect these contaminations?

Thanks and best regards

**Comment by tseemann** [comment]
Snippy is designed for clean isolate WGS only.   It will not call SNPs correctly because it needs `--minfrac 0.9` evidence to call a variant, and as you observed, you will have many mixed sites, which it will call "heterozygous" and not report. 

You can use the number of heterozygous genotypes `GT=0/1` in the VCF file as a guide to how badly mixed or contaminated the sample is, but Snippy does not do this for you, sorry.

In our lab we just reject the WGS result, and ask the sample to be regrown and a new colony pick be taken and sequenced.
