### ISSUE TITLE
paired end and single end

### ISSUE THREAD

**Issue by acebollada** [tseemann/snippy#356]
Dear all,
I have one question, is it possible run snippy at same time with fastq from two different sequence techniques (illumina and iontorrent), that ones are paired end and others are single end??

Thank you for your attention to this matter

Alberto Cebollada

**Comment by tseemann** [comment]
BWA MEM is not the best aligner for Ion Torrent data due to it's homopolymer errors. I don't think you will find any more SNPs using the Ion data compared to the Illumina.

That said, there is a way to possibly do what you want. You first need to interleave your Illumina R1/R2 into a single file, then append the ion torrent SE data, and then use
` --peil F         Reads, paired-end R1/R2 interleaved (default '')` option.

**Comment by acebollada** [comment]
Thank you very much for your response Torsten!
I had thought about whether it would be a good strategy aligning separately ilumina reads with BWA for example and ion torrent with tmap, afther this, we run the snippy with the bam files obtained. Do you think if we use this strategy is correct?

**Comment by tseemann** [comment]
I thought the Ion Suite came with its own variant calling tool?
Our old Ion Torrent setup had it years ago.

I would just call varaints with Snippy + Illumina --R1 --R2
Then try Snippy + Ion with --bam (from tmap)
And examine the VCF files and look for differences.
I doubt the Ion data will find any extra SNPs.

**Comment by vappiah** [comment]
Hi @tseemann 

I have some reads which after trimming generated paired reads and the unpaired single reads

I tried running snippy specifiy both R1 R2 and se but I got an error. 

Please advice.
