### ISSUE TITLE
Question: is it ok to use the core.aln file for raxml?

### ISSUE THREAD

**Issue by mearls999** [tseemann/snippy#362]
Hi there,

Very basic question (new to bioinformatics!)

As I understand it, the core.aln file produced by core snippy is a concatenated alignment of your core SNPs, i.e. if I'm working with 200 staph aureus (2.8 MB) isolates, the core.aln file might only be about 8,000 nt long. 

My question is: is it ok to use this file to make a ML tree using raxml? Specifically, does it matter that the scaling on the branches (substitutions per site) won't actually relate to the size of the staph aureus genome?

Thanks,

Megan

**Comment by tseemann** [comment]
`core.aln` is just the variant sites. 8000 snps for 200 staph genomes is normal.  if you use this the scale will be wrong because raxml will think the genome is only 8000nt long and it's all variable. raxml has special parameters to tell it that there are other "constant sites" (invariant positions) which it can use to correct the scale.

`core.full.aln` is the full reference genome with invariant sites. you can feed that to raxml and get the correct scale. not clear if it makes it slower to run - some tools are dumb and don't remove invariant sites and happily waste compute cycles computing empty results.

We use iqtree instead of raxml and combined with snp-sites tool it's easy to correct for invariant sites, but i think raxml has a similar setting. Nullarbor pipeline also automatically does this when it runs iqtree.

* https://bitsandbugs.org/2019/11/06/two-easy-ways-to-run-iq-tree-with-the-correct-number-of-constant-sites/
* https://github.com/andersgs/beast2_constsites

**Comment by mearls999** [comment]
Thanks for your reply, tseeman.

I have searched the giant raxml manual and can't find the option to specify constant sites. Do you happen to know the option for this?

Yes, I put the core.full.aln through raxml but via gubbins (because I wanted to remove recombination-associated SNPs) but it produces a tree with the branch scale as "no. of SNPs" instead of "subs per site". If I don't use Gubbins, it turns out fine (subs per site) but I would like to remove recombination-associated SNPs

Your iqtree+snp-sites approach sounds good. I will try it out next time!

**Comment by tseemann** [comment]
RAXML from a colleague:
```
You first need to add --asc-corr=stamatakis -q part to the command line.
part is a file with the following line:
[asc~count_inv_sites_core.txt], ASC_DNA, core=1-<length of alignment>
Then, you need a file called count_inv_sites_core.txt with: one line with space separated counts of invariable sites in the order A,C,G,T
```

RAXML-NG from me:
```
Stamatakis: e.g. --model GTR+G+ASC_STAM{1000/2000/3000/4000}
// 1000 invariant As, 2000 Cs, 3000 Gs, 4000 Ts
See also: https://github.com/amkozlov/raxml-ng/wiki/Input-data#evolutionary-model
```

**Comment by mearls999** [comment]
Thanks tseemann - I will both this and IQ-Tree.
