### ISSUE TITLE
is snippy suitable for RNA-seq

### ISSUE THREAD

**Issue by huangl07** [tseemann/snippy#397]
is snippy suitable for RNA-seq

**Comment by tseemann** [comment]
I have actually used Snippy for finding variants when i only had RNA-Seq data and no WGS data, and it worked fine. Of course `--mincov` etc still apply, and if a gene isn't expressed you won't be able to find SNPs in that gene, but sure, it pretty much works, because there are rarely introns in bacterial transripts.

Here is where we did it:  https://www.biorxiv.org/content/10.1101/058842v2
