### ISSUE TITLE
multiple references

### ISSUE THREAD

**Issue by plasmid02** [tseemann/snippy#82]
What is the way to specify multiple annotated reference molecules in the --ref command(e.g GBK files of chromosome and plasmids)?  Missed it when I was looking through the documentation.

Thanks!

**Comment by andersgs** [comment]
You need to `cat` them into a single file:

`cat seq1.gbk seq2.gbk ... seqN.gbk > all_seq.gbk`

`nullarbor.pl --ref all_seq.gbk ...`

**Comment by tseemann** [comment]
@plasmid02 yes, @andersgs is spot on. Snippy can handle 'multi-genbank' files.

**Comment by marsurro** [comment]
Hi Tseemann, 

I have a sort of an issue with Snippy and I hope that you could help me.

I have concatenated multiple reference sequences into one file. I then that file with --ref option to compare it against all of my query samples (paired end reads).
After completing all the runs I used snippy-core to do the core-alignment, and here is the issue - in the resulting core.full.aln I see all the corresponding samples but only one Reference fasta.
Is there any way of obtaining the core.full.aln file having all samples included but also all the references that I used (since in the variant tables for each sample I have variants found in each reference sequence).

I need to have all references included in that file so I can further use it for phylogenetic analysis.

Thank you!
Marius

**Comment by marsurro** [comment]
Hi again.

I managed to solve it with the ctgs option. 😊
