### ISSUE TITLE
Low frequency SNPs

### ISSUE THREAD

**Issue by elenamd** [tseemann/snippy#92]
Hi Torsten,

I am working with some isolates that present mutations only in 50% and 40% of the reads but I don't detect them by using snippy. If I run snippy with the options --mincov 5 and --minfrac going up to 0.2 I still don't pick up this mutations. What else I can change in the parameters to be able to detect these cases.

Thanks,

Elena

**Comment by ryjohnson09** [comment]
I just ran into the same issue...tried to set minfrac as low as 0.05 but failed to pick up these low frequency mutations. I can use bam-readcount to manually investigate allele frequencies in the bam/bam.bai, but only for snps. Would like to incorporate the additional variants as well (mnps, ins, del, complex).

**Comment by tseemann** [comment]
Snippy isn't really designed for this use-case.  We are interested in low freq vars too, but Snippy needs refactoring to support it.

You may want to look at PHEnix: https://github.com/phe-bioinformatics/PHEnix

Or the Hapflow protocol: http://mjsull.github.io/HapFlow/

**Comment by ryjohnson09** [comment]
Thanks Torsten...I'll definitely give these a try (I do like the looks of PHEnix). 

As a side note, do you think it would be problematic to simply take the snippy bam/bam.bai and gather the nucleotide frequencies at each snp location in order to find these low abundance variants? In a nut shell, I'm trying to see if a plate swipe of random bacteria from a water pipe contains a single strain, or if there are multiple strains from the same species (I have sequenced multiple single isolates, so I have an idea of where the strain specific snps lie). My current plan is to align the plate swipe miseq reads to a PacBio reference genome we generated (the same reference used to call snps for each individual isolate), and then extract the allele frequencies at each "strain-specific" snp site (I use [bam-readcount](https://github.com/genome/bam-readcount)). It's worked pretty well, but I'm worried I'm overlooking something...would love your feedback! I'll also be at ASMNGS if you want to chat there as well.

**Comment by tseemann** [comment]
@ryjohnson09 I think you may be interested in LoFreq: http://csb5.github.io/lofreq/

I've packaged it for Brew:  `brew install brewsci/bio/lofreq1

I'll be at ASM NGS 2018 too.
